### ISSUE TITLE
Can't install MambaVision via pip

### ISSUE THREAD

**Issue by Phues** [NVlabs/MambaVision#31]
When I do pip install mambavision I get the following error (I'm on windows 11 and my cuda version is 12.1):

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Benya\AppData\Local\Temp\pip-install-s7x2dj8y\mamba-ssm_d1e765297c3c471b8a6833c6f627b1a7\setup.py", line 100, in <module>
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
        File "C:\Users\Benya\AppData\Local\Temp\pip-install-s7x2dj8y\mamba-ssm_d1e765297c3c471b8a6833c6f627b1a7\setup.py", line 62, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output(
        File "C:\Users\Benya\anaconda3\envs\prj\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\Benya\anaconda3\envs\prj\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Benya\anaconda3\envs\prj\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Benya\anaconda3\envs\prj\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      torch.__version__  = 2.3.0+cu121

      [end of output]

**Comment by ahatamiz** [comment]
Thanks for sharing this error. Are you able to successfully install Mamba itself ?

**Comment by Phues** [comment]
If you mean the mamba-ssm package then no I was not able to able install it, I get this error 
![image](https://github.com/user-attachments/assets/3a2c7373-90a9-483f-b21e-fe85513d733e)

**Comment by yws-wxs** [comment]
How to solve this problem

**Comment by yws-wxs** [comment]
How to solve this problem   
![image](https://github.com/user-attachments/assets/4c8c312c-50a1-4e45-9ab0-a69b0d0b5ba2)

**Comment by ahatamiz** [comment]
Hi @Phues and @yws-wxs ,for now please install these requirements until the next pip release which addresses this issue:

```
pip install torch
pip install transformers
pip install timm
pip install Pillow
pip install requests
pip install mamba_ssm
```

**Comment by ahatamiz** [comment]
Hi @Phues and @yws-wxs 

The issue should be fixed now. Try by installing the new MambaVision package:
`pip install mambavision==1.1.0`
